name: Release script
on:
  push:
    tags:
      - v*.*-release
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: fetch
        run: git fetch --all --prune

      - name: exec release
        run: ls
