name: Release action
on:
  push:
    tags:
      - 'v*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout source'
        with:
          fetch-depth: 0

      - name: 'Run'
        run: ls