name: Release script
on:
  push:
    tags:
      - 'v*'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-push-tag@v1

      - name: exec release
        run: ls
